image: node:latest

cache:
  paths:
    - node_modules/

pages:
  variables:
    HOST_PREFIX: "banana-hackers.gitlab.io/store-db/"
  script:
    - cd _generator
    - npm ci
    - node .
  artifacts:
    paths:
      - public
  only:
    - master

test:
  variables:
    HOST_PREFIX: "banana-hackers.gitlab.io/store-db/"
  script:
    - cd _generator
    - npm ci
    - node .
  except:
    - master
