image: node:latest

cache:
  paths:
    - _generator/node_modules/

variables:
  GIT_DEPTH: "0" # disable shallow clone -> https://docs.gitlab.com/ee/ci/large_repositories/index.html#shallow-cloning

pages:
  variables:
    HOST_PREFIX: "banana-hackers.gitlab.io/store-db/"
  script:
    - cd _generator
    - npm ci
    - node .
  artifacts:
    paths:
      - public
  only:
    - master

test:
  variables:
    HOST_PREFIX: "banana-hackers.gitlab.io/store-db/"
  script:
    - cd _generator
    - npm ci
    - node .
  except:
    - master
